# Generated by Django 5.2.8 on 2025-11-16 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Día de la Semana')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden dentro de la semana (0-6)', verbose_name='Orden')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Día Plantilla',
                'verbose_name_plural': 'Días Plantilla',
                'db_table': 'dia_plantilla',
                'ordering': ['semana', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altura (m)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to='api.alumno', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Asignación de Plan',
                'verbose_name_plural': 'Asignaciones de Planes',
                'db_table': 'asignacion_plan',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DiaAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_especifica', models.DateField(verbose_name='Fecha Específica')),
                ('dia_semana', models.CharField(max_length=10, verbose_name='Día de la Semana')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('asignacion_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_asignados', to='api.asignacionplan', verbose_name='Asignación de Plan')),
                ('dia_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_asignados', to='api.diaplantilla', verbose_name='Día Plantilla')),
            ],
            options={
                'verbose_name': 'Día Asignado',
                'verbose_name_plural': 'Días Asignados',
                'db_table': 'dia_asignado',
                'ordering': ['fecha_especifica'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_hora_ejecucion', models.DateTimeField(verbose_name='Fecha y Hora de Ejecución')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('ritmo', models.CharField(blank=True, help_text='Ej: 5:30/km', max_length=20, verbose_name='Ritmo')),
                ('pulsaciones_promedio', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Pulsaciones Promedio')),
                ('pulsaciones_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Pulsaciones Máximas')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distancia (km)')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración (minutos)')),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, help_text='1-5 estrellas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('dia_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='api.diaasignado', verbose_name='Día Asignado')),
            ],
            options={
                'verbose_name': 'Ejecución de Entrenamiento',
                'verbose_name_plural': 'Ejecuciones de Entrenamiento',
                'db_table': 'ejecucion_entrenamiento',
                'ordering': ['-fecha_hora_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.CharField(blank=True, max_length=200, verbose_name='Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrenador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'entrenador',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='api.entrenador', verbose_name='Entrenador'),
        ),
        migrations.CreateModel(
            name='ImagenEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ejecuciones/%Y/%m/%d/', verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.ejecucionentrenamiento', verbose_name='Ejecución')),
            ],
            options={
                'verbose_name': 'Imagen de Ejecución',
                'verbose_name_plural': 'Imágenes de Ejecución',
                'db_table': 'imagen_ejecucion',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_semanas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (semanas)')),
                ('is_template', models.BooleanField(default=False, help_text='Marca si este plan es una plantilla reutilizable', verbose_name='Es Plantilla')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_entrenamiento', to='api.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Plan de Entrenamiento',
                'verbose_name_plural': 'Planes de Entrenamiento',
                'db_table': 'plan_entrenamiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asignacionplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='api.planentrenamiento', verbose_name='Plan'),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('detalles', models.TextField(blank=True, help_text='Ejemplo: 5x800m + 3x500m, recuperación 2min', verbose_name='Detalles')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='api.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'rutina',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='diaplantilla',
            name='rutina',
            field=models.ForeignKey(blank=True, help_text='Puede ser NULL para días de descanso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_plantilla', to='api.rutina', verbose_name='Rutina'),
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Semana')),
                ('nombre', models.CharField(blank=True, help_text='Ej: Semana de adaptación, Semana de carga', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='api.planentrenamiento', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'db_table': 'semana',
                'ordering': ['plan', 'numero_semana'],
            },
        ),
        migrations.AddField(
            model_name='diaplantilla',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_plantilla', to='api.semana', verbose_name='Semana'),
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('entrenador', models.ForeignKey(blank=True, help_text='NULL = tipo global, con valor = personalizado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_actividad_personalizados', to='api.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutinas', to='api.tipoactividad', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_entrenamiento', to='api.tipoactividad', verbose_name='Tipo de Actividad'),
        ),
        migrations.CreateModel(
            name='TipoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('entrenador', models.ForeignKey(blank=True, help_text='NULL = tipo global, con valor = personalizado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_rutina_personalizados', to='api.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Tipo de Rutina',
                'verbose_name_plural': 'Tipos de Rutina',
                'db_table': 'tipo_rutina',
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo_rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='api.tiporutina', verbose_name='Tipo de Rutina'),
        ),
        migrations.AddIndex(
            model_name='diaasignado',
            index=models.Index(fields=['asignacion_plan', 'fecha_especifica'], name='dia_asignad_asignac_acb47c_idx'),
        ),
        migrations.AddIndex(
            model_name='diaasignado',
            index=models.Index(fields=['completado'], name='dia_asignad_complet_c52042_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diaasignado',
            unique_together={('asignacion_plan', 'fecha_especifica')},
        ),
        migrations.AddIndex(
            model_name='ejecucionentrenamiento',
            index=models.Index(fields=['dia_asignado', 'fecha_hora_ejecucion'], name='ejecucion_e_dia_asi_c793b9_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['entrenador', 'created_at'], name='alumno_entrena_577068_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionplan',
            index=models.Index(fields=['alumno', 'estado'], name='asignacion__alumno__eea267_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionplan',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='asignacion__fecha_i_e235f2_idx'),
        ),
        migrations.AddIndex(
            model_name='semana',
            index=models.Index(fields=['plan', 'numero_semana'], name='semana_plan_id_854e11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semana',
            unique_together={('plan', 'numero_semana')},
        ),
        migrations.AddIndex(
            model_name='diaplantilla',
            index=models.Index(fields=['semana', 'orden'], name='dia_plantil_semana__018e76_idx'),
        ),
        migrations.AddIndex(
            model_name='diaplantilla',
            index=models.Index(fields=['dia_semana'], name='dia_plantil_dia_sem_c302a1_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoactividad',
            index=models.Index(fields=['entrenador', 'nombre'], name='tipo_activi_entrena_f7f662_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipoactividad',
            unique_together={('nombre', 'entrenador')},
        ),
        migrations.AddIndex(
            model_name='planentrenamiento',
            index=models.Index(fields=['entrenador', 'is_template'], name='plan_entren_entrena_4f9d34_idx'),
        ),
        migrations.AddIndex(
            model_name='planentrenamiento',
            index=models.Index(fields=['tipo_actividad'], name='plan_entren_tipo_ac_52d86d_idx'),
        ),
        migrations.AddIndex(
            model_name='tiporutina',
            index=models.Index(fields=['entrenador', 'nombre'], name='tipo_rutina_entrena_b82748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tiporutina',
            unique_together={('nombre', 'entrenador')},
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['entrenador', 'tipo_actividad'], name='rutina_entrena_aac2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['tipo_rutina'], name='rutina_tipo_ru_a506dc_idx'),
        ),
    ]
