# Generated by Django 5.2.8 on 2025-11-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el entrenador ha completado el proceso de pago/activación.', verbose_name='Activo por Pago'),
        ),
    ]
